title: Log
description: All my links
author: "Antti Polvivaara"

theme: minima

base_url: /lokikirja
repository: /AnttiPolvivaara/lokikirja

# Minima social links
github_username: AnttiPolvivaara
twitter_username: APolvivaara

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

exclude: 
    - README.md
