title: Log
description: This site is intended to work as an personal log and portfolio for my current projects and allow ease of access to the many links that are connected to me one way or another.
author: "Antti Polvivaara"

theme: minima

base_url: /lokikirja
repository: /AnttiPolvivaara/lokikirja

# Minima social links
github_username: AnttiPolvivaara
twitter_username: APolvivaara
linkedin_username: anttipolvivaara
google_scholar_username: Ssxk8acAAAAJ

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%d-%m-%Y"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

exclude: 
    - README.md
